### ISSUE TITLE
Automatically setup run configuration for LiteLoader Client

### ISSUE THREAD

**Issue by willies952002** [minecraft-dev/MinecraftDev#111]
This issue has manifested itself on 2 different systems with the same version of IDEA, same version of the Minecraft Development plugin, and nearly identical settings.

### Expected Behavior ###
LiteLoader Test Client Launches Correctly

### Observed Behavior ###
Test client fails to launch with [this error](https://gist.github.com/willies952002/b78e4f3d9aa9b5212f839c5925a0fd5a#file-)

### Plugin Version ###
2016-0.4.5

### [build.gradle](https://gist.github.com/willies952002/b78e4f3d9aa9b5212f839c5925a0fd5a#file-build-gradle) ###

(Run Configuration Available Only By Request)

**Comment by Mumfrey** [comment]
[Mixin](https://github.com/SpongePowered/Mixin) automatically disables the internal *reference map* (which is used to convert MCP names to notch names at runtime) when `GradleStart` is used to run the application. You are seeing the error because the startup class is not `GradleStart` and thus the refmap is still active. Because the refmap is still active, Mixin is converting references internally to notch names and this results in a crash.

To fix the issue:

* Ensure you are using `GradleStart` as the launch class
* Alternatively, forcibly disable the refmap by appending the JVM argument `-Dmixin.env.disableRefMap=true`

Maybe a suggestion to @DemonWav: if IntelliJ is somehow not calling `GradleStart` to launch the game, have McDevIntellij manually insert the above argument into the run configuration, assuming that's possible?

**Comment by DemonWav** [comment]
McDev doesn't currently automatically setup LiteLoader run configs. I'll chance this to a feature request.
