### ISSUE TITLE
Add option to automatically ungrab mouse

### ISSUE THREAD

**Issue by afdw** [minecraft-dev/MinecraftDev#132]
I suggest adding option that will ungrab mouse automatically when reaching breakpoint. At the moment I do this steps every time I'm using breakpoints:
1. Press `Alt+F8`
2. Type `Mouse.setGrabbed(false)`
3. Press Enter
4. Press Escape

I think this option will be useful because doing this steps takes much time.

**Comment by kashike** [comment]
I'm very confused. Could you please better explain what you mean?

**Comment by afdw** [comment]
Sorry, I was thinking that everyone who was debugging Minecraft related code had this problem. I mean: if you are debugging Minecraft client, when you join the world Minecraft grabs you cursor, so you you can't anymore see your cursor and you can't for example switch applications with mouse. If you open inventory (usually with pressing `E`), Minecraft will move cursor to the center of its window and ungrab it, so you can see the cursor. When you close inventory Mineraft will grab your cursor again. So if you place breakpoint in place that executed when mouse is grabbed, for example in tick() method of tile entity in place that executed only on server, then when JVM reaches this breakpoint, IDEA will not ungrab your mouse, so you can't move cursor, and you will have to do steps I describe in issue description.

You can see the problem with placing breakpoint is server side (here I mean effective side, not physical).

**Comment by Barteks2x** [comment]
For me the problem occurs only when the breakpoint is in the clientside code (ie. when client thread reaches the breakpoint). Some systems ungrab the mouse automatically when you do something like alt+tab, some systems unfortunately don't (all linux systems I have worked with don't do that, but it works fine on windows). With IDEA it's possible to workaround this bu using some keyboard shortcuts but it's very annoying to do, especially when done frequently.

So if it's possible, the plugin could evaluate `org.lwjgl.input.Mouse.setGrabbed(false)` when any breakpoint is hit and causes client thread to pause.

**Comment by Keridos** [comment]
:+1:

**Comment by DemonWav** [comment]
I'll have to do some digging into this one. First I need to replicate the issue. I've debugged MC clients before without this issue, so I need to find a way to actually replicate it.

**Comment by afdw** [comment]
@DemonWav What OS are you using?

**Comment by DemonWav** [comment]
@afdw Windows 10, macOS Sierra, and Arch Linux with Cinnamon.

**Comment by Barteks2x** [comment]
It shouldn't be too hard to reproduce it on linux - I used debian and now gentoo with Cinnamon and it happens to me. Adding breakpoint that is first hit by client thread should do it.

**Comment by Keridos** [comment]
Having the same issue here on arch linux 64 bit with cinnamon.

**Comment by DemonWav** [comment]
I think I've found a good way of testing this, but on macOS it doesn't seem to have this issue. I'll test in Linux later today.

**Comment by darkevilmac** [comment]
Any progress on this? I've been using openSUSE to develop lately and this is very much still an issue.

**Comment by incognitojam** [comment]
http://minecraft.gamepedia.com/Debug_screen#More_debug-keys

If you press `F3` + `P` it might resolve this issue.

**Comment by darkevilmac** [comment]
@IncognitoJam That doesn't solve the problem, in fact it makes it worse. The game pausing is what frees up your mouse. If this is enabled then the game will never get to a point that it will unlock the cursor.

**Comment by Niko-sk2x** [comment]
@IncognitoJam I think you misunderstood the problem here. The problem is that Minecraft never gets the chance to pause, because the debugger stops it. The game can't do anything by itself to ungrab the mouse.

**Comment by incognitojam** [comment]
@Barteks2x @darkevilmac Okay no problem

**Comment by DenWav** [comment]
I will look into this more soon, I haven't done anything on it since last time I commented on this issue.

**Comment by stephan-gh** [comment]
I implemented this a while ago, but for some reason the debugger freezes completely after you've paused the program a few times.  I have no idea why that is happening. See https://github.com/minecraft-dev/MinecraftDev/commit/252858af7a570b4ee4e7c59a4d2c9841340e3cdf

**Comment by Mumfrey** [comment]
How are you marshalling the calls between the threads? If you're just calling the lwjgl method from within the debugger thread then it could be freezing because you're creating a deadlock within lwjgl itself.

**Comment by stephan-gh** [comment]
@Mumfrey
Yeah, I believe it runs from the debugger thread, although only after the JVM has already been suspended (so no other code is running at this point). However, I could imagine that it could indeed create a deadlock if the JVM was suspended within a call to lwjgl.

**Comment by Mumfrey** [comment]
Well that, but I meant that the underlying native hWnd is owned by the main/window thread, avoiding this kind of thing is GUI applications 101. Calling `setGrabbed` calls `setCursorPosition` in the implementation which invokes `nSetCursorPosition` on windows which is a native function which [calls the OS SetCursorPos function](https://github.com/LWJGL/lwjgl/blob/master/src/native/windows/org_lwjgl_opengl_Display.c#L479). It then calls `grabMouse` in the implementation which itself calls `WindowsMouse::grab` which itseld calls `resetCursorClipping` which delegates to native [clipCursor](https://github.com/LWJGL/lwjgl/blob/8bb7dfefc628972e71568fac243503d8984555fc/src/native/windows/org_lwjgl_opengl_Display.c#L267) and that's not even the end of it.... `updateCursor` does more things with setting the cursor natively...

There's all kinds of things that could be possibly wrong with causing these native functions to run from a different thread whilst not pumping messages on the window thread. My point is you might not even be creating a JVM deadlock, you could be creating a deadlock natively somehow by causing these methods to be called the main thread suspended.

Ultimately you could be looking at a deadlock in the JVM caused by calling this on the wrong thread, or some kind of deadlock between the JVM and the OS.

**Comment by Mumfrey** [comment]
Thinking about it, the issue could be that you're not actually marshalling this call to *intellij's* GUI thread. I assume that intellij has some kind of `EventQueue::invokeLater` equivalent?

**Comment by stephan-gh** [comment]
> Thinking about it, the issue could be that you're not actually marshalling this call to intellij's GUI thread. I assume that intellij has some kind of EventQueue::invokeLater equivalent?

Is IntelliJ IDEA's GUI related to this in any way? I only call `Mouse.setGrabbed` in the Minecraft JVM (since that blocks the mouse pointer when the JVM is freezed). IntelliJ IDEA's UI is not involved, Minecraft (or the OS) should just release the mouse pointer so it's usable again.

**Comment by Mumfrey** [comment]
> Minecraft (or the OS) should just release the mouse pointer so it's usable again.

What?

"Grabbing" the mouse is not an OS-level functionality, if the thread managing the grabbing is not running, the mouse isn't "grabbed", it's just hidden!

The mouse **cursor** is an OS resource. The cursor's current location is readable and writable by applications. To implement "grabbing", the window just hides the mouse cursor and resets the mouse cursor position every frame. So there is no "releasing" to be done. The cursor needs to be **unhidden** but it's "released" implicitly by the failure to pump messages (and thus process the mouse "grabbing" by virtue of the application not currently pulling the mouse cursor location back into the bounds of its window.

My point was that in general UI operations should be performed by UI threads and not by other threads. You can "ungrab" the mouse via just calling the OS methods to show the mouse cursor if the grabbing thread isn't running.

LWJGL has pluggable platform implementations for all its supported platforms, on Windows this calls out native via JNI, on linux it looks like it ensures it's not fucking over AWT by using some native AWT lock, but that means you're still doing UI operations on a non-UI thread.

Intellij is almost certainly going to provide some functionality like `EventQueue::invokeLater` which lets you marshal stuff onto the UI thread for the application. If you're going to interact with the UI you should do it there.

**Comment by stephan-gh** [comment]
@Mumfrey
I apologize, but I'm slightly confused: Are you are saying is that, instead of running `Mouse.setGrabbed` in the Minecraft JVM, I should make the mouse visible again directly from the IntelliJ IDEA JVM? That might be a bit difficult because IntelliJ IDEA doesn't use LWJGL so I don't have the same method.

Right now I'm not running any UI operation in the IntelliJ IDEA JVM. I instruct the debugger to run `Mouse.setGrabbed` in the JVM where the Minecraft client is running (because that's what hides the mouse). Of course, it should run on Minecraft's UI thread, but at this point the UI thread is already suspended (and probably also busy doing other stuff).

**Comment by Mumfrey** [comment]
Addendum: apparently mac os has the functionality to "actually" grab the mouse via [CGAssociateMouseAndMouseCursorPosition](https://developer.apple.com/documentation/coregraphics/1454486-cgassociatemouseandmousecursorpo?language=objc) so for mac os it would be necessary to (in mac os terminology) "reconnect the cursor to the mouse".

**Comment by Mumfrey** [comment]
@Minecrell the "JVM" you run the operations in is irrelevant since the minecraft client thread is suspended when you hit a break point. Thus the "grabbing" logic is just not running, all that's happening is that the mouse cursor is invisible (and in the case of mac os, the cursor location is also "disconnected" from the mouse).

LWJGL is doing two things for "grabbing": It's hiding the mouse cursor (native, calls out to the OS to do this) and then in the message pump it's consuming mouse events into a buffer (mouse delta) and then constantly re-snapping the visible cursor to the middle of the window (again, by making native calls to the OS).

Now, depending on the OS the rules vary for what resources/API calls you are *allowed* to make from non-ui threads, but if you aren't sure, then you just absolutely avoid interacting with UI resources of any kind outside of a thread which owns a window, because *that thread* can pump events *from* the OS and other threads cannot.

What I am telling you is that it doesn't matter what JVM is involved, but if you're experiencing random lock-ups after making these calls on a random thread then your first troubleshooting action should be to make the calls (the native calls out to the OS to unhide the mouse cursor) on a UI thread, any UI thread it doesn't matter because you only have one operating system.

The side effect of not doing it via the minecraft runtime would be that LWJGL "thinks" the mouse is grabbed and thus runs the grab logic but doesn't hide the cursor, but escaping that situation would be as simple as opening any GUI and closing it again because it will attempt to "re grab" the cursor and of course will re-hide it at that point.

**Comment by afdw** [comment]
> Addendum: apparently mac os has the functionality to "actually" grab the mouse via CGAssociateMouseAndMouseCursorPosition so for mac os it would be necessary to (in mac os terminology) "reconnect the cursor to the mouse".

Same for Linux with X Window System I think: [XGrabPointer and XUngrabPointer](https://linux.die.net/man/3/xgrabpointer), called [here](https://github.com/LWJGL/lwjgl/blob/8bb7dfefc628972e71568fac243503d8984555fc/src/native/linux/opengl/org_lwjgl_opengl_Display.c#L632).

**Comment by Mumfrey** [comment]
> Same for Linux with X Window System I think: XGrabPointer and XUngrabPointer, called here.

Makes sense, then my statement above about grabbing not being an os-level function is only true for windows. Though it still doesn't address the threading issue.

**Comment by stephan-gh** [comment]
@Mumfrey Thanks a lot for the explanation! I guess I was just thinking about what I need to change in the code, while you were explaining why it's freezing (at least one possible cause).

I understand that we should do this on the UI thread, however that's kind of tricky: We can't do this in the Minecraft JVM, and as far as I can tell from what you've posted above, doing it directly from IntelliJ IDEA is also complicated because it requires platform-specific native code. I don't think it's worth it to pull `lwjgl` into MinecraftDev just to ungrab the mouse, also assuming lwjgl will even run within IntelliJ IDEA...

**Comment by afdw** [comment]
But as I can see from code, Minecraft's main and UI thread (where it creates Display, for example) is named "Client thread". So it's possible to ungrab mouse at least if current thread is it, no?

**Comment by Mumfrey** [comment]
No because that thread is suspended.

**Comment by afdw** [comment]
Suspended, but you still can execute methods on it, it's working like these calls were in place of breakpoint, if I understood it correctly.

**Comment by Mumfrey** [comment]
If that's really the case, that you can run commands on the actual suspended thread, then yes it should be fine to invoke `Mouse::setGrabbed` on it, as long as the identity of the thread is confirmed as the client thread. When the VM hits a breakpoint all of its threads are suspended, so the identity of the target thread would need to be confirmed.

**Comment by afdw** [comment]
@Minecrell which OS are you using? Works mostly fine on Linux with X11, tried many times, no hangs.

**Comment by stephan-gh** [comment]
@afdw It happens when I set a breakpoint somewhere and then keep press `Step Into` several times. After a few times I can't step any further, and the debugger doesn't work properly anymore.

The weird thing is that a thread dump doesn't even show any problem... `Mouse.setGrabbed` isn't running anywhere.

**Comment by stephan-gh** [comment]
As far as I can see, it's actually freezing somewhere else. `Mouse.setGrabbed` completes successfully when I run into the debugger freezes.

**Comment by afdw** [comment]
Why even is it doing `Mouse.setGrabbed(false)` when pressing `Step Into`?

**Comment by stephan-gh** [comment]
It does it whenever the JVM is getting suspended. `Step into` will resume the JVM, do one step and pause it again.

**Comment by afdw** [comment]
But MC shouldn't grab mouse when `Step into`, so it's not needed. Can you do not it then?

**Comment by stephan-gh** [comment]
I run `Mouse.isGrabbed()` to check if it's already ungrabbed, but as I said, it doesn't even freeze on the call to `Mouse.is/setGrabbed`. Something else is causing it.

**Comment by afdw** [comment]
I'm not sure, but this seems to work for me: [grab.patch](https://github.com/minecraft-dev/MinecraftDev/files/1309198/grab.patch.txt)

**Comment by stephan-gh** [comment]
@afdw Were you able to reproduce the freezes when using `Step Into` before the patch? And this patch fixes it for you?

**Comment by afdw** [comment]
Yes, I reproduced it, if by freezing you mean blocking most of debugger buttons (except `Drop Frame`). Yes, it fixes it for me.

**Comment by stephan-gh** [comment]
Alright. I'll check your patch as soon as I have time. Thanks for testing!

**Comment by kashike** [comment]
The patch above seems to work for me. :+1:

**Comment by stephan-gh** [comment]
@afdw @kashike Can you test if my branch (https://github.com/minecraft-dev/MinecraftDev/tree/ungrab-mouse) is working correctly now? I've integrated @afdw's changes with some additional cleanup.

**Comment by afdw** [comment]
@Minecrell seems to work for me.

**Comment by waifutech** [comment]
`setxkbmap -option grab:break_actions`
then do `xdotool key XF86Ungrab` in your guake or something after breakpoint is triggered

**Comment by thedarkcolour** [comment]
This doesn't work on new Minecraft versions
