### ISSUE TITLE
Config files are displayed as errored

### ISSUE THREAD

**Issue by sokratis12GR** [minecraft-dev/MinecraftDev#143]
Looks like it confuses .cfg (ATs | Access Transformers) with .cfg (config files for mods)
![image](https://cloud.githubusercontent.com/assets/12274096/22345022/28604b44-e407-11e6-9bab-d8ece74b57b0.png)

**Comment by DemonWav** [comment]
As far as I know this has already been dealt with, but the setting may persist in your IDE.
Go to `Settings -> Editor -> File Types` and the top (or near the top) entry should be `Access Transformers`. In the bottom panel, remove `*.cfg`. It really should be `*_at.cfg`, but that may not be their either (you can add it if you want), since this is handled with [this code](https://github.com/minecraft-dev/MinecraftDev/blob/2016.3/src/main/java/com/demonwav/mcdev/platform/mcp/McpProjectComponent.java#L55).

**Comment by sokratis12GR** [comment]
That worked, yeah I guess .cfg only shouldn't be the case
