### ISSUE TITLE
Allow auto-completion and validation for InjectionPoint @At targets

### ISSUE THREAD

**Issue by DemonWav** [minecraft-dev/MinecraftDev#212]
`@At` can take the keywords, or the name of a class that extends `org.spongepowered.asm.mixin.injection`.

Another point to note, the keywords are declared by `@AtCode` on `InjectionPoint` classes, so we should auto-complete based off of those rather than hard-coding known keywords. Would handle user-added names.

**Comment by stephan-gh** [comment]
> Another point to note, the keywords are declared by `@AtCode` on `InjectionPoint` classes, so we should auto-complete based off of those rather than hard-coding known keywords. Would handle user-added names.

🤔 

https://github.com/minecraft-dev/MinecraftDev/blob/5ca157504de2b48226b18f16e0bc5d14597e92d7/src/main/kotlin/com/demonwav/mcdev/platform/mixin/reference/InjectionPointType.kt#L61-L65

Since we do have support for custom `@AtCode`s, I'm not sure if it's worth implementing completion for classes. `@AtCode` is much more convenient anyway.
