### ISSUE TITLE
Translation and i18n

### ISSUE THREAD

**Issue by Katrix-** [minecraft-dev/MinecraftDev#61]
I'm pretty sure IntelliJ already has support for this, however I can't seem to find out how to make use of it. Would be neat if the .lang files would be autodetected here.

Don't know how it is with other platforms and translation.

**Comment by DemonWav** [comment]
Can you elaborate more on what you mean? I'm a little confused. If you mean the plugin should support i18n and allow translation, that is something we're working on and do plan on supporting. If you're referring to i18n support in your code somehow, then I'm not sure what you mean.

Also, by .lang files, are you talking about .properties files? Where are they located for them to be auto detected?

**Comment by Katrix-** [comment]
Was mostly thinking about supporting translation for the plugins themselves. 

I don't know how it is with the other platforms, but when working with forge to support translation you place your `.lang` files (`.lang`, not `.properties`), in the resource folder `assets/<modid>/lang/` and name the file after the locale. so for example you could have `assets/<modid>/lang/en_US.lang`. At the moment IntelliJ just treats `.lang` files as normal text files. What I was thinking is that it would be neat if it actually recognized them as translations.

**Comment by DemonWav** [comment]
Thanks for the info. I'll give a look at it and see what can be done.

**Comment by PaleoCrafter** [comment]
I've already talked about this with kashike some time ago, but I've been working on my own Minecraft development IDEA plugin way before this plugin became a thing. I focused on Forge mods and implementing proper `.lang` file support was one of my primary goals. I've implemented a custom file type (because `.properties` files use a more general grammar that doesn't match the Vanilla parser) and various supporting features.

If you're interested, I could try to refactor it to make it PR-ready for this project.

Some of the more advanced (and interesting) features are as follows:
 - Reference generation and auto-completion for calls to `I18n.format` and methods calling that (i.e. a custom method that prepends the modid would also be supported)
  - Same for constructor calls to `TextComponentTranslation` and subclasses
  - Brings full renaming support for lang keys with it
 - Code folding for referenced translations (i.e. `I18n.format("tile.furnace.name")` would get folded to `"Furnace"`)
 - Localisation difference detection: If lang keys in a localisation (e.g. `de_DE.lang`) do not match the default `en_US.lang`, a notification will pop up and the missing keys can be automatically added with their default value

**Comment by DemonWav** [comment]
That would be awesome, I'd love the PR if you can manage the time to do it.

**Comment by Katrix-** [comment]
@PaleoCrafter Any progress on this?

**Comment by PaleoCrafter** [comment]
Free time has been more scarce than I had assumed, lately. I'll probably only get to work on this during my Christmas vacations, but I promise that I'll get you guys something by then!

**Comment by DemonWav** [comment]
@PaleoCrafter feel free to hop ping me IRC if you have any specific questions about how the project is structure.

**Comment by DenWav** [comment]
This is now done.
