### ISSUE TITLE
Nbt reader/writer

### ISSUE THREAD

**Issue by kinggoesgaming** [minecraft-dev/MinecraftDev#73]
with minecraft, forge and sponge(where needed), data is stored as nbt. It would be nice if a built in nbt reader/writer is made available with the plugin

**Comment by DemonWav** [comment]
There are plenty of great standalone NBT viewers that already work, I don't see much use for something like this.  I'm more focused on creating new things that aren't yet available for people. If you need an NBT viewer, they are readily available for you.

**Comment by DemonWav** [comment]
So I had a change of heart about this and have put in quite a lot of work into a text-based NBT editor. It follows somewhat closely to the "Mojangson" format, with some extensions as well. I've called it NBTT (NBT Text) and I've developed a lexer and parser for it, annotations, type-aware syntax highlighting, automatic reading and writing from and to NBT files, etc. This is what it looks like in practice so far:

![](http://i.imgur.com/0D6gZTu.png)

I _may_ consider also building a GUI counterpart as well. I do think the text-based editor makes more sense, however, since it's in an IDE context. However, even considering how much effort I've put into the text editor so far (currently the NBT package accounts for ~3800 LOC), I still consider that easier than building complex dynamic GUIs. It will depend on what people say they want.

**Comment by kinggoesgaming** [comment]
Aye aye... That's my ~~man~~ demon!

**Comment by gabizou** [comment]
@DemonWav Should make it optional to expand children. There are some areas where an 11Mb dat file will balloon the IDE ;)

**Comment by DemonWav** [comment]
@gabizou way ahead of you. Tags with a child count of greater than 50 are automatically folded.

**Comment by DemonWav** [comment]
I may make that number configurable or something, though. I haven't figured out the best way of handling very large data sets yet.

**Comment by stephan-gh** [comment]
Pretty sure we can close this now that https://github.com/minecraft-dev/MinecraftDev/pull/214 is merged.
