### ISSUE TITLE
Warn when comparing itemstack to null

### ISSUE THREAD

**Issue by Katrix** [minecraft-dev/MinecraftDev#99]
In Minecraft 1.11 itemstacks are never null, instead they have a specific empty stack. Instead if checking if an itemstack is null, it should do a `stack.isEmpty()` check. This will make updating big 1.10 mods to 1.11 much easier.

**Comment by DemonWav** [comment]
I wish this was true as well for Bukkit, but of course it's not. Valid for all other platforms, though.

**Comment by Katrix-** [comment]
Just remember that this only covers 1.11 forward, unlike other stuff witch applies to all forge versions.

On Nov 29, 2016 4:47 PM, Kyle Wood <notifications@github.com> wrote:

I wish this was true as well for Bukkit, but of course it's not. Valid for all other platforms, though.

**Comment by MiniDigger** [comment]
it kinda applies to bukkit too, if you use the NMS itemstack class and not bukkit's.

**Comment by gabizou** [comment]
It's not valid for Sponge, since the API already had the concept of `ItemTypes.NONE`. Otherwise, yes, if you are integrating with internals, it will apply for both MCP and Bukkit.

**Comment by DemonWav** [comment]
Actually, this is more complex than I originally thought. Take the following hypothetical code snippet:

```java
ItemStack stack = null;
try {
    stack = getItemStackButThisMightThrowAnException();
} catch (Exception e) {
    doErrorLogging(e);
}

if (stack == null) {
    doSpecialAction();
} else {
    doNormalAction();
}
```

Now, obviously this does bring up the idea that perhaps there should be another inspection to suggest using `ItemStack stack = ItemStack.EMPTY;` instead of `ItemStack stack = null;`, but this code is still valid, and so it the null check. I'm thinking I may be able to look into using IntelliJ's built-in nullability checks to determine if it's an actually valid null check before triggering the warning.

**Comment by liach** [comment]
@DemonWav :trollface: 
```java
Optional<Object> optional = null;
try {
    optional = getItemStackButThisMightThrowAnException();
} catch (Exception e) {
    doErrorLogging(e);
}

if (optional == null) {
    doSpecialAction();
} else {
    doNormalAction();
}
```

Ask users to use `ActionResult<ItemStack>` or `DataTransactionResult<ItemStack>`.
